Repository Infomaniak/android-rich-html-editor, pull requests merged in 2024-06, with the labels that each got.

#1 Initializes an empty project that builds
  .github/workflows/android.yml
  .github/workflows/auto-author-assign.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/rebase-default-branch.yml
  .gitignore
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  rich-html-editor/build.gradle.kts
  rich-html-editor/consumer-rules.pro
  rich-html-editor/proguard-rules.pro
  sample/build.gradle.kts
  sample/proguard-rules.pro
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/MainActivity.kt
  sample/src/main/res/drawable/ic_launcher_background.xml
  sample/src/main/res/drawable/ic_launcher_foreground.xml
  sample/src/main/res/layout/activity_main.xml
  sample/src/main/res/layout/fragment_editor_sample.xml
  sample/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  sample/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  sample/src/main/res/mipmap-hdpi/ic_launcher.webp
  sample/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  sample/src/main/res/mipmap-mdpi/ic_launcher.webp
  sample/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  sample/src/main/res/mipmap-xhdpi/ic_launcher.webp
  sample/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  sample/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  sample/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  sample/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  sample/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  sample/src/main/res/navigation/nav_graph.xml
  sample/src/main/res/values-night/colors.xml
  sample/src/main/res/values-night/themes.xml
  sample/src/main/res/values-v23/themes.xml
  sample/src/main/res/values/colors.xml
  sample/src/main/res/values/dimens.xml
  sample/src/main/res/values/strings.xml
  sample/src/main/res/values/style.xml
  sample/src/main/res/values/themes.xml
  sample/src/main/res/xml/data_extraction_rules.xml
  sample/src/main/res/xml/network_security_config.xml
  settings.gradle.kts
Labels: good first issue

#4 Update to kotlin 2.0
  gradle/libs.versions.toml
Labels: quick

#5 Update libraries
  gradle/libs.versions.toml
Labels: quick

#6 Prevent entering a blank display text for the URL display text
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
Labels: quick

#14 Keep the keyboard opened on configuration changed
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/Extensions.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/KeyboardOpener.kt
Labels: enhancement

#15 Save edited HTML on configuration changed
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleViewModel.kt
Labels: enhancement

#7 Update gradle settings
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  rich-html-editor/build.gradle.kts
  rich-html-editor/consumer-rules.pro
  sample/build.gradle.kts
Labels: enhancement

#18 Jitpack setup
  jitpack.yml
  rich-html-editor/build.gradle.kts
Labels: enhancement

#9 Add font size customization
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsColor.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/JsExecutableMethod.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/res/layout/fragment_editor_sample.xml
Labels: enhancement

#10 Support ordered and unordered lists
  rich-html-editor/src/main/assets/define_listeners.js
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorStatuses.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/StatusCommand.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/res/drawable/ic_ordered_list.xml
  sample/src/main/res/drawable/ic_unordered_list.xml
  sample/src/main/res/layout/fragment_editor_sample.xml
Labels: enhancement

#11 Support subscript and superscript
  rich-html-editor/src/main/assets/define_listeners.js
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorStatuses.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/StatusCommand.kt
  rich-html-editor/src/main/res/drawable/ic_subscript.xml
  rich-html-editor/src/main/res/drawable/ic_superscript.xml
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/res/layout/fragment_editor_sample.xml
Labels: enhancement

#12 Make toolbar visibly scrollable
  sample/src/main/res/layout/fragment_editor_sample.xml
Labels: quick

#13 Support indent and outdent
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/StatusCommand.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/res/drawable/ic_indent.xml
  sample/src/main/res/drawable/ic_outdent.xml
  sample/src/main/res/layout/fragment_editor_sample.xml
Labels: enhancement, quick

#19 Move subscript and superscript drawables to the correct module
  sample/src/main/res/drawable/ic_subscript.xml
  sample/src/main/res/drawable/ic_superscript.xml
Labels: quick

#20 Add missing initial copyright
  .idea/copyright/Editor_copyright.xml
  .idea/copyright/profiles_settings.xml
  rich-html-editor/src/main/assets/editor_template.html
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/DocumentInitializer.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorStatuses.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/Extensions.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsColor.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/Justification.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebViewClient.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/StatusCommand.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/JsExecutableMethod.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/JsExecutor.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/JsLifecycleAwareExecutor.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/KeyboardOpener.kt
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/ScriptCssInjector.kt
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleViewModel.kt
  sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/MainActivity.kt
  sample/src/main/res/color/background_editor_button.xml
  sample/src/main/res/drawable/ic_indent.xml
  sample/src/main/res/drawable/ic_justify_center.xml
  sample/src/main/res/drawable/ic_justify_full.xml
  sample/src/main/res/drawable/ic_justify_left.xml
  sample/src/main/res/drawable/ic_justify_right.xml
  sample/src/main/res/drawable/ic_launcher_background.xml
  sample/src/main/res/drawable/ic_launcher_foreground.xml
  sample/src/main/res/drawable/ic_ordered_list.xml
  sample/src/main/res/drawable/ic_outdent.xml
  sample/src/main/res/drawable/ic_redo.xml
  sample/src/main/res/drawable/ic_subscript.xml
  sample/src/main/res/drawable/ic_superscript.xml
  sample/src/main/res/drawable/ic_undo.xml
  sample/src/main/res/drawable/ic_unordered_list.xml
  sample/src/main/res/layout/activity_main.xml
  sample/src/main/res/layout/create_link_text_input.xml
  sample/src/main/res/layout/fragment_editor_sample.xml
  sample/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  sample/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  sample/src/main/res/navigation/nav_graph.xml
  sample/src/main/res/values-night/colors.xml
  sample/src/main/res/values-night/themes.xml
  sample/src/main/res/values-v23/themes.xml
  sample/src/main/res/values/colors.xml
  sample/src/main/res/values/dimens.xml
  sample/src/main/res/values/strings.xml
  sample/src/main/res/values/style.xml
  sample/src/main/res/values/themes.xml
  sample/src/main/res/xml/data_extraction_rules.xml
  sample/src/main/res/xml/network_security_config.xml
Labels: quick

#23 Remove unnecessary argumentName value and add clarifying comment
  rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/StatusCommand.kt
Labels: quick
